api/urls.py
from django.conf.urls import patterns, url

from api import views

urlpatterns = patterns('',
                       # /api/leagues/
                       url(r'^leagues/$', views.leagues, name='leagues'),
                       # /api/leagues/1/
                       url(r'^leagues/(?P<league_id>\d+)/$', views.league_info, name='league-info'),
                       # /api/teams/
                       url(r'^teams/$', views.teams, name='teams'),
                       # /api/teams/1/
                       url(r'^teams/(?P<team_id>\d+)/$', views.team_info, name='team-info'),
                       # /api/players/
                       url(r'^players/$', views.players, name='players'),
                       # /api/players/1/
                       url(r'^players/(?P<player_id>\d+)/$', views.player_info, name='player-info'),
                       )

basketball/urls.py
from django.conf.urls import patterns, url

from basketball import views

urlpatterns = patterns('',
                       # /basketball/
                       url(r'^$', views.leagues, name='leagues'),
                       # Commissioner only - /basketball/leagues/create
                       url(r'^leagues/create$', views.create_league, name='create-league'),
                       # /basketball/leagues/1/
                       url(r'^leagues/(?P<league_id>\d+)/$', views.league_info, name='league-info'),
                       # Commissioner only - /basketball/leagues/1/edit
                       url(r'^leagues/(?P<league_id>\d+)/edit$', views.edit_league_info, name='edit-league-info'),
                       # Commissioner only - /basketball/leagues/1/draft
                       url(r'^leagues/(?P<league_id>\d+)/draft$', views.draft_league, name='draft-league'),
                       # Commissioner only - /basketball/leagues/1/delete
                       url(r'^leagues/(?P<league_id>\d+)/delete$', views.delete_league, name='delete-league'),
                       # /basketball/teams/1/
                       url(r'^teams/(?P<team_id>\d+)/$', views.team_info, name='team-info'),
                       # /basketball/players/1/
                       url(r'^players/(?P<player_id>\d+)/$', views.player_info, name='player-info'),
                       # /basketball/players/1/edit
                       url(r'^players/(?P<player_id>\d+)/edit$', views.edit_player_info, name='edit-player-info'),
                       # /basketball/register/
                       url(r'^register/$', views.register, name='registration'),
                       # /basketball/login/
                       url(r'^login/$', views.login, name='login'),
                       # /basketball/logout/
                       url(r'^logout/$', views.logout, name='logout'),
                       # Commissioner only - /basketball/commissioner/
                       url(r'^leagues/commissioner/$', views.commissioner_dashboard, name='commissioner-dashboard'),
                       )

league_manager/urls.py
from django.conf.urls import patterns, include, url

from basketball import views

urlpatterns = patterns('',
                       # root '/'
                       url(r'^$', views.leagues, name='index'),
                       # include basketball app's urls
                       url(r'^basketball/', include('basketball.urls', namespace='basketball')),
                       # include api app's urls
                       url(r'^api/', include('api.urls', namespace='api'))
                       )

basketball/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class League(models.Model):
    name = models.CharField(max_length=50, unique=True)
    is_active = models.BooleanField(default=True)
    max_number_teams = models.PositiveSmallIntegerField(default=8, validators=[MinValueValidator(2)])
    min_number_players_per_team = models.PositiveSmallIntegerField(default=5, validators=[MinValueValidator(5)])

    date_created = models.DateTimeField(auto_now_add=True)
    signup_allowed = models.BooleanField(default=True)

    def __unicode__(self):
        return self.name


class Team(models.Model):
    name = models.CharField(max_length=50)
    league = models.ForeignKey(League, limit_choices_to={'is_active': True})

    def __unicode__(self):
        return self.name


class Player(models.Model):
    GUARD = 'G'
    FORWARD = 'F'
    CENTER = 'C'
    POSITION_CHOICES = (
        (GUARD, 'Guard'),
        (FORWARD, 'Forward'),
        (CENTER, 'Center'),
    )
    position = models.CharField(max_length=1,
                                choices=POSITION_CHOICES,
                                default=GUARD)
    name = models.CharField(max_length=50)
    age = models.PositiveSmallIntegerField(validators=[MaxValueValidator(100)])
    leagues = models.ManyToManyField(League, through='LeagueMembership',
                                     limit_choices_to={'is_active': True, 'signup_allowed': True})
    user = models.OneToOneField(User)

    # Not required
    about = models.TextField(max_length=250, blank=True)

    def register_for_league(self, league):
        self.assign_to_team_in_league(league, None)

    def assign_to_team_in_league(self, league, team):
        try:
            league_membership = self.leaguemembership_set.get(league=league)
            league_membership.team = team
        except LeagueMembership.DoesNotExist:
            league_membership = LeagueMembership(league=league, player=self, team=team)

        league_membership.save()

    def __unicode__(self):
        return self.name


class LeagueMembership(models.Model):
    league = models.ForeignKey(League)
    player = models.ForeignKey(Player)

    date_joined = models.DateTimeField(auto_now_add=True)

    # Null if Player just signed up for League and hasn't been drafted to a team
    team = models.ForeignKey(Team, null=True, blank=True)

basketball/forms.py
from django.forms import ModelForm, ValidationError
from django.contrib.auth.models import User, BaseUserManager
from django.contrib.auth.forms import UserCreationForm

from basketball.models import Player, League


class LeagueForm(ModelForm):
    class Meta:
        model = League
        fields = ['name', 'max_number_teams', 'min_number_players_per_team', 'is_active', 'signup_allowed']


class PlayerForm(ModelForm):
    class Meta:
        model = Player
        fields = ['name', 'age', 'position', 'about', 'leagues']


class UserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise ValidationError('Email addresses must be unique.')
        return email

    def clean_password(self):
        password = self.cleaned_data.get('password')
        if len(password) < 6:
            raise ValidationError('Password must be 6 characters or longer')
        return super(UserForm, self).clean_password()

basketball/views.py
from random import shuffle

from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import user_passes_test
from django.contrib.auth import authenticate
from django.contrib.auth.models import User, BaseUserManager
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

from basketball.models import Player, League, Team
from basketball.forms import LeagueForm, PlayerForm, UserForm


def is_superuser(user):
    return user.is_superuser


def leagues(request):
    league_list = League.objects.all()
    context = {'league_list': league_list}
    return render(request, 'basketball/index.html', context)


@user_passes_test(is_superuser)
def create_league(request):
    if request.method == 'GET':
        league_form = LeagueForm()
        context = {'league_form': league_form}
    elif request.method == 'POST':
        league_form = LeagueForm(request.POST)
        if league_form.is_valid():
            league = league_form.save()
            return HttpResponseRedirect(reverse('basketball:league-info', args=[league.pk]))
        else:
            context = {'league_form': league_form}

    return render(request, 'basketball/create_league.html', context)


def league_info(request, league_id):
    league = get_object_or_404(League, pk=league_id)
    context = {'league': league}
    return render(request, 'basketball/league.html', context)


@user_passes_test(is_superuser)
def edit_league_info(request, league_id):
    league = get_object_or_404(League, pk=league_id)
    league_form = LeagueForm(instance=league)
    if request.method == 'POST':
        league_form = LeagueForm(request.POST, instance=league)
        if league_form.is_valid():
            league = league_form.save()
            return HttpResponseRedirect(reverse('basketball:league-info', args=[league.pk]))

    context = {'league_form': league_form, 'league': league}
    return render(request, 'basketball/edit_league.html', context)


@user_passes_test(is_superuser)
def draft_league(request, league_id):
    league = get_object_or_404(League, pk=league_id)
    context = {'league': league}
    if request.method == 'POST':
        result = enact_draft(league)
        if result:
            return result
        context['error'] = True

    return render(request, 'basketball/draft_league.html', context)


def enact_draft(league):
    # Idea is to create a random permutation of players in the league,
    # then assign them to teams, giving the first few teams at most 1 extra player,
    # depending on the number of players registered and minimum number of players per team.
    players = list(league.player_set.all())
    shuffle(players)
    num_players = len(players)
    max_num_teams = league.max_number_teams
    num_teams_possible = num_players / league.min_number_players_per_team
    if num_teams_possible >= max_num_teams:
        num_teams = max_num_teams
    elif num_teams_possible >= 2:
        num_teams = num_teams_possible
    else:
        return None

    num_players_per_equal_team = num_players / num_teams
    num_teams_unequal = num_players % num_teams
    Team.objects.filter(league=league).delete()
    for i in xrange(0, num_teams):
        team_name = 'Team %d' % (i+1)
        team = Team.objects.create(name=team_name, league=league)
        team.save()

        if i < num_teams_unequal:
            start = i*num_players_per_equal_team + i
            end = start + num_players_per_equal_team + 1
        else:
            start = i*num_players_per_equal_team + num_teams_unequal
            end = start + num_players_per_equal_team

        for player in players[start:end]:
            player.assign_to_team_in_league(league, team)

    return HttpResponseRedirect(reverse('basketball:league-info', args=[league.pk]))


@user_passes_test(is_superuser)
def delete_league(request, league_id):
    league = get_object_or_404(League, pk=league_id)
    if request.method == 'POST':
        league.delete()
        return HttpResponseRedirect(reverse('basketball:leagues'))

    context = {'league': league}
    return render(request, 'basketball/delete_league.html', context)


def team_info(request, team_id):
    team = get_object_or_404(Team, pk=team_id)
    context = {'team': team}
    return render(request, 'basketball/team.html', context)


def player_info(request, player_id):
    player = get_object_or_404(Player, pk=player_id)
    context = {'player': player}
    return render(request, 'basketball/player.html', context)


def edit_player_info(request, player_id):
    player = get_object_or_404(Player, pk=player_id)
    user = request.user

    if not user.is_superuser and (not user.player or user.player.pk != player.pk):
        return HttpResponse('Unauthorized', status=401)

    player_form = PlayerForm(instance=player)
    if request.method == 'POST':
        player_form = PlayerForm(request.POST, instance=player)
        if player_form.is_valid():
            player = player_form.save(commit=False)
            player.leaguemembership_set.filter(league__signup_allowed=True, league__is_active=True).delete()
            for league_id in request.POST.getlist('leagues'):
                league = League.objects.get(pk=league_id)
                player.register_for_league(league)
            player.save()

            return HttpResponseRedirect(reverse('basketball:player-info', args=[player.pk]))

    context = {'player_form': player_form, 'player': player}
    return render(request, 'basketball/edit_player.html', context)


def register(request):
    if request.method == 'GET':
        player_form = PlayerForm()
        user_form = UserForm()
        context = {'player_form': player_form, 'user_form': user_form}
    elif request.method == 'POST':
        player_form = PlayerForm(request.POST)
        user_form = UserForm(request.POST)
        if player_form.is_valid() and user_form.is_valid():
            user = user_form.save()
            player = Player.objects.create(name=player_form.cleaned_data['name'], age=player_form.cleaned_data['age'],
                                           position=player_form.cleaned_data['position'],
                                           about=player_form.cleaned_data['about'], user=user)
            for league_id in request.POST.getlist('leagues'):
                league = League.objects.get(pk=league_id)
                player.register_for_league(league)

            return HttpResponseRedirect(reverse('basketball:login'))
        else:
            context = {'player_form': player_form, 'user_form': user_form}

    return render(request, 'basketball/register.html', context)


def login(request):
    if request.method == 'GET':
        user = request.user
        if user.is_authenticated():
            if user.is_superuser:
                return HttpResponseRedirect(reverse('basketball:commissioner-dashboard'))
            else:
                return HttpResponseRedirect(reverse('basketball:edit-player-info', args=[user.player.pk]))
        redirect_next = request.GET.get('next', reverse('basketball:leagues'))
        context = {'error': False, 'next': redirect_next}
    elif request.method == 'POST':
        username = request.POST.get('username', '')
        password = request.POST.get('password', '')
        try:
            username = User.objects.get(email=BaseUserManager.normalize_email(username)).get_username
        except User.DoesNotExist:
            pass
        user = authenticate(username=username, password=password)
        if user is not None:
            auth_login(request, user)
            redirect_next = request.POST.get('next')
            if not redirect_next:
                redirect_next = reverse('basketball:leagues')
            return HttpResponseRedirect(redirect_next)
        else:
            context = {'error': True}

    return render(request, 'basketball/login.html', context)


def logout(request):
    auth_logout(request)
    return HttpResponseRedirect('/basketball/')


@user_passes_test(is_superuser)
def commissioner_dashboard(request):
    return render(request, 'basketball/commissioner.html')

basketball/templates/basketball/commissioner.html
{% extends 'base.html' %}

{% block title %}Commissioner Dashboard{% endblock %}

{% block breadcrumb-page %}
  <li><a href="{% url 'basketball:leagues' %}">Basketball</a></li>
  <li class="active">Commissioner Dashboard</li>
{% endblock breadcrumb-page %}

{% block content %}
  <h1>Commissioner Dashboard</h1>
  <ul>
    <li><a href="{% url 'basketball:create-league' %}">Create new league</a></li>
  </ul>
{% endblock content %}

basketball/templates/basketball/create_league.html
{% extends 'base.html' %}

{% block title %}Create Basketball League{% endblock %}

{% block breadcrumb-page %}
  <li><a href="{% url 'basketball:leagues' %}">Basketball</a></li>
  <li class="active">Create League</li>
{% endblock breadcrumb-page %}

{% block content %}
  <h1>Create League</h1>
  {% if league_form %}
    <form method="post" action="{% url 'basketball:create-league' %}" role="form">
      {% csrf_token %}
      <div class="form-group">
      {{ league_form.as_p }}
      </div>
      <button type="submit" class="btn btn-default">Create</button>
    </form>
  {% else %}
    <p>There was a problem with the create league form.</p>
  {% endif %}
{% endblock content %}

basketball/templates/basketball/delete_league.html
{% extends 'base.html' %}

{% block title %}Delete Basketball League{% endblock %}

{% block breadcrumb-page %}
  <li><a href="{% url 'basketball:leagues' %}">Basketball</a></li>
  <li class="active">Delete League</li>
{% endblock breadcrumb-page %}

{% block content %}
  <h1>Delete League</h1>
  {% if league %}
    <p>Are you sure you want to delete the league named "{{ league.name }}" and all teams associated with it?</p>
    <div>
      <form class="form-inline" method="post" action="{% url 'basketball:delete-league' league.pk %}">
        {% csrf_token %}
        <a class="btn btn-default" href="{% url 'basketball:league-info' league.pk %}">No</a>
        <button type="submit" class="btn btn-danger">Delete</button>
      </form>
    </div>
  {% else %}
    <p>League not found.</p>
  {% endif %}
{% endblock content %}

basketball/templates/basketball/draft_league.html
{% extends 'base.html' %}

{% block title %}Draft Basketball League{% endblock %}

{% block breadcrumb-page %}
  <li><a href="{% url 'basketball:leagues' %}">Basketball</a></li>
  <li class="active">Draft League</li>
{% endblock breadcrumb-page %}

{% block content %}
  <h1>Draft League</h1>
  {% if league %}
    {% if error %}
      <div class="alert-warning">There was a problem drafting, there are only {{ league.player_set.count }}
        players registered for this league, but that is not enough to create a league with at least 2 teams of
        {{ league.min_number_players_per_team }}!</div>
    {% endif %}
    <p>Are you sure you want to auto-draft the league named "{{ league.name }}"?
      It might be a good idea to first close registration, to lessen any confusion!</p>
    <div>
      <form class="form-inline" method="post" action="{% url 'basketball:draft-league' league.pk %}">
        {% csrf_token %}
        <a class="btn btn-default" href="{% url 'basketball:league-info' league.pk %}">No</a>
        <button type="submit" class="btn btn-success">Draft</button>
      </form>
    </div>
  {% else %}
    <p>League not found.</p>
  {% endif %}
{% endblock content %}

basketball/templates/basketball/edit_league.html
{% extends 'base.html' %}

{% block title %}Edit Basketball League{% endblock %}

{% block breadcrumb-page %}
  <li><a href="{% url 'basketball:leagues' %}">Basketball</a></li>
  <li class="active">Edit League</li>
{% endblock breadcrumb-page %}

{% block content %}
  <h1>Edit League</h1>
  {% if league_form %}
    <form method="post" action="{% url 'basketball:edit-league-info' league.pk %}" role="form">
      {% csrf_token %}
      <div class="form-group">
        {{ league_form.as_p }}
      </div>
      <button type="submit" class="btn btn-default">Save</button>
    </form>
  {% else %}
    <p>There was a problem with the create league form.</p>
  {% endif %}
{% endblock content %}

basketball/templates/basketball/edit_player.html
{% extends 'base.html' %}

{% block title %}Edit Player Info{% endblock %}

{% block breadcrumb-page %}
  <li><a href="{% url 'basketball:leagues' %}">Basketball</a></li>
  <li class="active">Edit Player Info</li>
{% endblock breadcrumb-page %}

{% block content %}
  <h1>Edit Player Info</h1>
  {% if player_form and player %}
    <form method="post" action="{% url 'basketball:edit-player-info' player.pk %}" role="form">
      {% csrf_token %}
      <div class="form-group">
        {{ player_form.as_p }}
      </div>
      <button type="submit" class="btn btn-default">Save</button>
    </form>
  {% else %}
    <p>There was a problem with the create league form.</p>
  {% endif %}
{% endblock content %}

basketball/templates/basketball/index.html
{% extends 'base.html' %}

{% block title %}Basketball Leagues{% endblock %}

{% block breadcrumb-page %}
  <li><a href="{% url 'basketball:leagues' %}">Basketball</a></li>
  <li class="active">Leagues</li>
{% endblock breadcrumb-page %}

{% block content %}
  <h1>Leagues</h1>
  {% if league_list %}
    <ul>
      {% for league in league_list %}
        {% if league.is_active %}
          <li><a href="{% url 'basketball:league-info' league.pk %}">{{ league.name }}</a></li>
        {% endif %}
      {% endfor %}
    </ul>
  {% else %}
    <p>No leagues exist yet.</p>
  {% endif %}
{% endblock content %}

basketball/templates/basketball/league.html
{% extends 'base.html' %}

{% block title %}
  {% if league %}
    {{ league.name }}
  {% else %}
    League Not Found
  {% endif %}
{% endblock %}

{% block breadcrumb-page %}
  <li><a href="{% url 'basketball:leagues' %}">Basketball</a></li>
  <li class="active">League</li>
{% endblock breadcrumb-page %}

{% block content %}
  {% if league %}
    <h1>{{ league.name }}</h1>
  {% endif %}

  {% if user.is_superuser %}
    <div>
      <a href="{% url 'basketball:draft-league' league.pk %}"><button type="button" class="btn">Auto-Draft</button></a>
      <a href="{% url 'basketball:edit-league-info' league.pk %}"><button type="button" class="btn btn-warning">Edit</button></a>
      <a href="{% url 'basketball:delete-league' league.pk %}"><button type="button" class="btn btn-danger">Delete</button></a>
    </div>
  {% endif %}

  {% if league.team_set.count > 0 %}
    <ul>
      {% for team in league.team_set.all %}
        <li><a href="{% url 'basketball:team-info' team.pk %}">{{ team.name }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No teams exist in this league yet.</p>
  {% endif %}
{% endblock content %}

basketball/templates/basketball/league_created.html
{% extends 'base.html' %}

{% block title %}Basketball League Created{% endblock %}

{% block breadcrumb-page %}
  <li><a href="{% url 'basketball:leagues' %}">Basketball</a></li>
  <li class="active">League Created</li>
{% endblock breadcrumb-page %}

{% block content %}
  <h1>League Created</h1>
  {% if league %}
    <p>League "{{ league.name }}" now exists!</p>
  {% else %}
    <p>League does not exist.</p>
  {% endif %}
{% endblock content %}

basketball/templates/basketball/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block breadcrumb-page %}
  <li class="active">Login</li>
{% endblock breadcrumb-page %}

{% block content %}
  <h1>Login</h1>
  {% if error %}
    <div class="alert-warning">Either the username or password supplied was incorrect. Please try again.</div>
  {% endif %}
  <form method="post" action="{% url 'basketball:login' %}" role="form">
    {% csrf_token %}
    <div class="form-group">
      {% if next %}
      <input type="hidden" name="next" value="{{ next }}"/>
      {% endif %}
      <label for="username">Username/Email address</label>
      <input type="text" class="form-control" name="username" placeholder="username/email"/>
      <label for="password">Password</label>
      <input type="password" class="form-control" name="password" placeholder="password"/>
    </div>
    <button type="submit" class="btn btn-default">Login</button>
  </form>
{% endblock content %}

basketball/templates/basketball/player.html
{% extends 'base.html' %}

{% block title %}
  {% if player %}
    {{ player.name }}
  {% else %}
    Player Not Found
  {% endif %}
{% endblock %}

{% block breadcrumb-page %}
  <li><a href="{% url 'basketball:leagues' %}">Basketball</a></li>
  <li class="active">Player</li>
{% endblock breadcrumb-page %}

{% block content %}
  {% if player %}
    <h1>{{ player.name }}</h1>
    {% if user.is_superuser or user.player and user.player.pk == player.pk %}
      <div>
        <a href="{% url 'basketball:edit-player-info' player.pk %}"><button type="button" class="btn btn-warning">Edit</button></a>
      </div>
    {% endif %}
    <ul>
      <li>Age: {{ player.age }}</li>
      <li>Position: {{ player.get_position_display }}</li>
      <li>
        {% if player.leaguemembership_set.count > 0 %}
          Teams:
          <ul>
            {% for membership in player.leaguemembership_set.all %}
              <li>
              {% if membership.team %}
                {{ membership.team.name }}
              {% else %}
                Waiting to placed on a team
              {% endif %}
              in the {{ membership.league.name }} league
              </li>
            {% endfor %}
          </ul>
        {% else %}
          {{ player.name }} doesn't seem to be on any teams or signed up for any leagues.
        {% endif %}
      </li>
      <li>About {{ player.name }}:  {{ player.about }}</li>
    </ul>
  {% else %}
    <p>No players are on this team right now.</p>
  {% endif %}
{% endblock content %}

basketball/templates/basketball/register.html
{% extends 'base.html' %}

{% block title %}Register{% endblock %}

{% block breadcrumb-page %}
  <li><a href="{% url 'basketball:leagues' %}">Basketball</a></li>
  <li class="active">Register</li>
{% endblock breadcrumb-page %}

{% block content %}
  <h1>Register</h1>
  {% if user_form and player_form %}
    <form method="post" action="{% url 'basketball:registration' %}" role="form">
      {% csrf_token %}
      <div class="form-group">
        {{ user_form.as_p }}
        {{ player_form.as_p }}
      </div>
      <button type="submit" class="btn btn-default">Register</button>
    </form>
  {% else %}
    <p>There was a problem with the create league form.</p>
  {% endif %}
{% endblock content %}

basketball/templates/basketball/team.html
{% extends 'base.html' %}

{% block title %}
  {% if team %}
    {{ team.name }}
  {% else %}
    Team Not Found
  {% endif %}
{% endblock %}

{% block breadcrumb-page %}
  <li><a href="{% url 'basketball:leagues' %}">Basketball</a></li>
  {% if team %}
    <li><a href="{% url 'basketball:league-info' team.league.pk %}">{{ team.league.name }}</a></li>
  {% endif %}
  <li class="active">Team</li>
{% endblock breadcrumb-page %}

{% block content %}
  {% if team %}
    <h1>{{ team.name }}</h1>
  {% endif %}

  {% if team.leaguemembership_set.count > 0 %}
    <ul>
      {% for membership in team.leaguemembership_set.all %}
        <li><a href="{% url 'basketball:player-info' membership.player.pk %}">{{ membership.player.name }}</a></li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No players are on this team right now.</p>
  {% endif %}
{% endblock content %}