api/urls.py
from django.conf.urls import patterns, url

from api import views

urlpatterns = patterns('',
                       # /api/leagues/
                       url(r'^leagues/$', views.leagues, name='leagues'),
                       # /api/leagues/1/
                       url(r'^leagues/(?P<league_id>\d+)/$', views.league_info, name='league-info'),
                       # /api/teams/
                       url(r'^teams/$', views.teams, name='teams'),
                       # /api/teams/1/
                       url(r'^teams/(?P<team_id>\d+)/$', views.team_info, name='team-info'),
                       # /api/players/
                       url(r'^players/$', views.players, name='players'),
                       # /api/players/1/
                       url(r'^players/(?P<player_id>\d+)/$', views.player_info, name='player-info'),
                       )

basketball/urls.py
from django.conf.urls import patterns, url

from basketball import views

urlpatterns = patterns('',
                       # /basketball/
                       url(r'^$', views.leagues, name='leagues'),
                       # Commissioner only - /basketball/leagues/create
                       url(r'^leagues/create$', views.create_league, name='create-league'),
                       # /basketball/leagues/1/
                       url(r'^leagues/(?P<league_id>\d+)/$', views.league_info, name='league-info'),
                       # Commissioner only - /basketball/leagues/1/edit
                       url(r'^leagues/(?P<league_id>\d+)/edit$', views.edit_league_info, name='edit-league-info'),
                       # Commissioner only - /basketball/leagues/1/draft
                       url(r'^leagues/(?P<league_id>\d+)/draft$', views.draft_league, name='draft-league'),
                       # Commissioner only - /basketball/leagues/1/delete
                       url(r'^leagues/(?P<league_id>\d+)/delete$', views.delete_league, name='delete-league'),
                       # /basketball/teams/1/
                       url(r'^teams/(?P<team_id>\d+)/$', views.team_info, name='team-info'),
                       # /basketball/players/1/
                       url(r'^players/(?P<player_id>\d+)/$', views.player_info, name='player-info'),
                       # /basketball/players/1/edit
                       url(r'^players/(?P<player_id>\d+)/edit$', views.edit_player_info, name='edit-player-info'),
                       # /basketball/register/
                       url(r'^register/$', views.register, name='registration'),
                       # /basketball/login/
                       url(r'^login/$', views.login, name='login'),
                       # /basketball/logout/
                       url(r'^logout/$', views.logout, name='logout'),
                       # Commissioner only - /basketball/commissioner/
                       url(r'^leagues/commissioner/$', views.commissioner_dashboard, name='commissioner-dashboard'),
                       )

league_manager/urls.py
from django.conf.urls import patterns, include, url

from basketball import views

urlpatterns = patterns('',
                       # root '/'
                       url(r'^$', views.leagues, name='index'),
                       # include basketball app's urls
                       url(r'^basketball/', include('basketball.urls', namespace='basketball')),
                       # include api app's urls
                       url(r'^api/', include('api.urls', namespace='api'))
                       )

templates/base.html
{% load static from staticfiles %}
<!DOCTYPE html>

<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]> <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]> <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->

<head>
  <meta charset="utf-8">
  <!-- [if it IE]> <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> <![endif]-->

  <title>
    {% block title %}{% endblock title %} | League Manager
  </title>

  {% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
  {% endblock stylesheets %}

  {% block page_styles %}{% endblock page_styles %}

  {% block js %}
    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
  {% endblock js %}

  {% block page_js %}{% endblock page_js %}
</head>

<body>

<!-- navigation -->
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#basketball-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index' %}">League Manager</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="basketball-collapse">
      <ul class="nav navbar-nav navbar-left">
        <li><a href="{% url 'basketball:leagues' %}">Basketball</a></li>
      </ul>
      {% if not user or user.is_anonymous %}
        <form class="navbar-form navbar-right" method="post" action="{% url 'basketball:login' %}">
          {% csrf_token %}
          <div class="form-group">
            {% if next %}
              <input type="hidden" name="next" value="{{ next }}"/>
            {% endif %}
            <input type="text" class="form-control" name="username" placeholder="username/email">
            <input type="password" class="form-control" name="password" placeholder="password">
          </div>
          <button type="submit" class="btn btn-default">Login</button>
        </form>
        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'basketball:registration' %}">Register</a></li>
        </ul>
      {% else %}
        <ul class="nav navbar-nav navbar-right">
          <li><a href="
            {% if user.is_superuser %}
              {% url 'basketball:commissioner-dashboard' %}
            {% else %}
              {% url 'basketball:player-info' user.player.pk %}
            {% endif %}">
            Logged in as {{ user.get_username }}</a></li>
          <li><a href="{% url 'basketball:logout' %}">Logout</a></li>
        </ul>
      {% endif %}
    </div>
  </div>
</nav>

{% block body %}
  <div class="container">
    <div class="row">
      {% block breadcrumbs %}
        <ul class="breadcrumb">
          <li><a href="{% url 'index' %}">Home</a></li>
          {% block breadcrumb-page %}{% endblock breadcrumb-page %}
        </ul>
      {% endblock breadcrumbs %}
    </div>
    <div class="row">
      <div class="span9 offset2">
        {% block content %}
          <h1>Placeholder</h1>
        {% endblock content %}
      </div>
    </div>
  </div>
{% endblock body %}

</body>

</html>